// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/


// TAO_IDL - Generated from
// /home/xuchang/chang_ws/OpenDDS-3.9/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:635

#ifndef _TAO_IDL_MESSENGERTYPESUPPORTS_ZIBLQD_CPP_
#define _TAO_IDL_MESSENGERTYPESUPPORTS_ZIBLQD_CPP_


#include "MessengerTypeSupportS.h"

#endif /* ifndef */

